
package com.scoa.roadrunner.connector.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RR13Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RR13Soap {


    /**
     * This method gets the Fares for the Reservation. Inputs:  Airport short code, ZipCode , Passengers  fore arrival and departure legs. 
     * 
     * @param discAmt
     * @param queryString
     * @param depDate
     * @param depAirport
     * @param arvZip
     * @param depZip
     * @param arvAirport
     * @param discCode
     * @param arvPessanger
     * @param depPessanger
     * @param arvDate
     * @return
     *     returns com.scoa.roadrunner.connector.api.GetFareForReservationResponse.GetFareForReservationResult
     */
    @WebMethod(operationName = "GetFareForReservation", action = "http://tempuri.org/GetFareForReservation")
    @WebResult(name = "GetFareForReservationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFareForReservation", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetFareForReservation")
    @ResponseWrapper(localName = "GetFareForReservationResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetFareForReservationResponse")
    public com.scoa.roadrunner.connector.api.GetFareForReservationResponse.GetFareForReservationResult getFareForReservation(
        @WebParam(name = "DepAirport", targetNamespace = "http://tempuri.org/")
        String depAirport,
        @WebParam(name = "DepZip", targetNamespace = "http://tempuri.org/")
        String depZip,
        @WebParam(name = "DepPessanger", targetNamespace = "http://tempuri.org/")
        String depPessanger,
        @WebParam(name = "DepDate", targetNamespace = "http://tempuri.org/")
        String depDate,
        @WebParam(name = "ArvAirport", targetNamespace = "http://tempuri.org/")
        String arvAirport,
        @WebParam(name = "ArvZip", targetNamespace = "http://tempuri.org/")
        String arvZip,
        @WebParam(name = "ArvPessanger", targetNamespace = "http://tempuri.org/")
        String arvPessanger,
        @WebParam(name = "ArvDate", targetNamespace = "http://tempuri.org/")
        String arvDate,
        @WebParam(name = "QueryString", targetNamespace = "http://tempuri.org/")
        String queryString,
        @WebParam(name = "DiscCode", targetNamespace = "http://tempuri.org/")
        String discCode,
        @WebParam(name = "DiscAmt", targetNamespace = "http://tempuri.org/")
        String discAmt);

    /**
     * This method for authentication and Login.  Username and Password.
     * 
     * @param userName
     * @param password
     * @return
     *     returns com.scoa.roadrunner.connector.api.CheckLoginResponse.CheckLoginResult
     */
    @WebMethod(operationName = "CheckLogin", action = "http://tempuri.org/CheckLogin")
    @WebResult(name = "CheckLoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckLogin", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.CheckLogin")
    @ResponseWrapper(localName = "CheckLoginResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.CheckLoginResponse")
    public com.scoa.roadrunner.connector.api.CheckLoginResponse.CheckLoginResult checkLogin(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * This method allows getting email password reminder. 
     * 
     * @param userEmailAddress
     * @return
     *     returns com.scoa.roadrunner.connector.api.ForgotPasswordResponse.ForgotPasswordResult
     */
    @WebMethod(operationName = "ForgotPassword", action = "http://tempuri.org/ForgotPassword")
    @WebResult(name = "ForgotPasswordResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ForgotPassword", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.ForgotPassword")
    @ResponseWrapper(localName = "ForgotPasswordResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.ForgotPasswordResponse")
    public com.scoa.roadrunner.connector.api.ForgotPasswordResponse.ForgotPasswordResult forgotPassword(
        @WebParam(name = "UserEmailAddress", targetNamespace = "http://tempuri.org/")
        String userEmailAddress);

    /**
     * This method allows create new reservation.
     * 
     * @param arvStreetNumber
     * @param charterArv
     * @param charterDep
     * @param arvFee
     * @param depService
     * @param custID
     * @param arvService
     * @param redemptionAmt
     * @param depGratuity
     * @param depFee
     * @param arvFltTime
     * @param arvStreet
     * @param arvPassenger
     * @param specialServicesJourneyType
     * @param depPickUp
     * @param travelerEmail
     * @param specialinst
     * @param travelerFName
     * @param depDirections
     * @param mailTo
     * @param depServiceidNew
     * @param restype1
     * @param specialServiceamt
     * @param discCode
     * @param fltType
     * @param cardType
     * @param clientId
     * @param discount
     * @param isWindowID
     * @param depFlt
     * @param pmtMode
     * @param arvCancel
     * @param cZip
     * @param travellerID
     * @param cccid
     * @param arvFlt
     * @param travelerLName
     * @param discAmt
     * @param specialServiceIDDep
     * @param depPickupTime
     * @param arvZip
     * @param depZip
     * @param arvAirline
     * @param depPassenger
     * @param infoID
     * @param pmtDetails
     * @param conf
     * @param billTo
     * @param depUnit
     * @param couponEmail
     * @param complexArv
     * @param ccTypeID
     * @param travelercellno
     * @param flyingTo
     * @param arvAirport
     * @param arvAP
     * @param ccExpDate
     * @param arvPickupTime
     * @param restypedetail
     * @param custType
     * @param cCname
     * @param depDate
     * @param arvUnit
     * @param depAP
     * @param arvCity
     * @param travelerWorkPhno
     * @param origin
     * @param travelerHomePhno
     * @param surcharge
     * @param arvDate
     * @param depStreet
     * @param depCity
     * @param depCancel
     * @param ip
     * @param depAirline
     * @param isSendEmail
     * @param reqArvTime
     * @param arvGratuity
     * @param arvServiceidNew
     * @param depStreetNumber
     * @param reqType
     * @param arvDirections
     * @param complexDep
     * @param depFltTime
     * @param ccNum
     * @param specialServiceIDArv
     * @param resType
     * @return
     *     returns com.scoa.roadrunner.connector.api.SaveReservationResponse.SaveReservationResult
     */
    @WebMethod(operationName = "SaveReservation", action = "http://tempuri.org/SaveReservation")
    @WebResult(name = "SaveReservationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveReservation", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.SaveReservation")
    @ResponseWrapper(localName = "SaveReservationResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.SaveReservationResponse")
    public com.scoa.roadrunner.connector.api.SaveReservationResponse.SaveReservationResult saveReservation(
        @WebParam(name = "CustID", targetNamespace = "http://tempuri.org/")
        String custID,
        @WebParam(name = "TravellerID", targetNamespace = "http://tempuri.org/")
        String travellerID,
        @WebParam(name = "CustType", targetNamespace = "http://tempuri.org/")
        String custType,
        @WebParam(name = "ResType", targetNamespace = "http://tempuri.org/")
        String resType,
        @WebParam(name = "ArvDate", targetNamespace = "http://tempuri.org/")
        String arvDate,
        @WebParam(name = "ArvAirport", targetNamespace = "http://tempuri.org/")
        String arvAirport,
        @WebParam(name = "ArvPassenger", targetNamespace = "http://tempuri.org/")
        String arvPassenger,
        @WebParam(name = "ArvPickupTime", targetNamespace = "http://tempuri.org/")
        String arvPickupTime,
        @WebParam(name = "ArvFee", targetNamespace = "http://tempuri.org/")
        String arvFee,
        @WebParam(name = "ArvGratuity", targetNamespace = "http://tempuri.org/")
        String arvGratuity,
        @WebParam(name = "Discount", targetNamespace = "http://tempuri.org/")
        String discount,
        @WebParam(name = "Conf", targetNamespace = "http://tempuri.org/")
        String conf,
        @WebParam(name = "SpecialServiceamt", targetNamespace = "http://tempuri.org/")
        String specialServiceamt,
        @WebParam(name = "ArvService", targetNamespace = "http://tempuri.org/")
        String arvService,
        @WebParam(name = "ArvZip", targetNamespace = "http://tempuri.org/")
        String arvZip,
        @WebParam(name = "SpecialServiceIDArv", targetNamespace = "http://tempuri.org/")
        String specialServiceIDArv,
        @WebParam(name = "RedemptionAmt", targetNamespace = "http://tempuri.org/")
        String redemptionAmt,
        @WebParam(name = "CardType", targetNamespace = "http://tempuri.org/")
        String cardType,
        @WebParam(name = "CCNum", targetNamespace = "http://tempuri.org/")
        String ccNum,
        @WebParam(name = "CCname", targetNamespace = "http://tempuri.org/")
        String cCname,
        @WebParam(name = "CCExpDate", targetNamespace = "http://tempuri.org/")
        String ccExpDate,
        @WebParam(name = "CCCID", targetNamespace = "http://tempuri.org/")
        String cccid,
        @WebParam(name = "CCTypeID", targetNamespace = "http://tempuri.org/")
        String ccTypeID,
        @WebParam(name = "CZip", targetNamespace = "http://tempuri.org/")
        String cZip,
        @WebParam(name = "ReqType", targetNamespace = "http://tempuri.org/")
        String reqType,
        @WebParam(name = "InfoID", targetNamespace = "http://tempuri.org/")
        String infoID,
        @WebParam(name = "PmtMode", targetNamespace = "http://tempuri.org/")
        String pmtMode,
        @WebParam(name = "PMTDetails", targetNamespace = "http://tempuri.org/")
        String pmtDetails,
        @WebParam(name = "ISWindowID", targetNamespace = "http://tempuri.org/")
        String isWindowID,
        @WebParam(name = "ArvCity", targetNamespace = "http://tempuri.org/")
        String arvCity,
        @WebParam(name = "SpecialServicesJourneyType", targetNamespace = "http://tempuri.org/")
        String specialServicesJourneyType,
        @WebParam(name = "TravelerFName", targetNamespace = "http://tempuri.org/")
        String travelerFName,
        @WebParam(name = "TravelerLName", targetNamespace = "http://tempuri.org/")
        String travelerLName,
        @WebParam(name = "TravelerHomePhno", targetNamespace = "http://tempuri.org/")
        String travelerHomePhno,
        @WebParam(name = "TravelerWorkPhno", targetNamespace = "http://tempuri.org/")
        String travelerWorkPhno,
        @WebParam(name = "Travelercellno", targetNamespace = "http://tempuri.org/")
        String travelercellno,
        @WebParam(name = "IP", targetNamespace = "http://tempuri.org/")
        String ip,
        @WebParam(name = "DepZip", targetNamespace = "http://tempuri.org/")
        String depZip,
        @WebParam(name = "DepService", targetNamespace = "http://tempuri.org/")
        String depService,
        @WebParam(name = "DepPickUp", targetNamespace = "http://tempuri.org/")
        String depPickUp,
        @WebParam(name = "ArvStreetNumber", targetNamespace = "http://tempuri.org/")
        String arvStreetNumber,
        @WebParam(name = "DepStreetNumber", targetNamespace = "http://tempuri.org/")
        String depStreetNumber,
        @WebParam(name = "ArvStreet", targetNamespace = "http://tempuri.org/")
        String arvStreet,
        @WebParam(name = "DepStreet", targetNamespace = "http://tempuri.org/")
        String depStreet,
        @WebParam(name = "ArvUnit", targetNamespace = "http://tempuri.org/")
        String arvUnit,
        @WebParam(name = "DepUnit", targetNamespace = "http://tempuri.org/")
        String depUnit,
        @WebParam(name = "ArvDirections", targetNamespace = "http://tempuri.org/")
        String arvDirections,
        @WebParam(name = "DepDirections", targetNamespace = "http://tempuri.org/")
        String depDirections,
        @WebParam(name = "ComplexArv", targetNamespace = "http://tempuri.org/")
        String complexArv,
        @WebParam(name = "ComplexDep", targetNamespace = "http://tempuri.org/")
        String complexDep,
        @WebParam(name = "ArvAP", targetNamespace = "http://tempuri.org/")
        String arvAP,
        @WebParam(name = "DepAP", targetNamespace = "http://tempuri.org/")
        String depAP,
        @WebParam(name = "ArvFlt", targetNamespace = "http://tempuri.org/")
        String arvFlt,
        @WebParam(name = "DepFlt", targetNamespace = "http://tempuri.org/")
        String depFlt,
        @WebParam(name = "DepPickupTime", targetNamespace = "http://tempuri.org/")
        String depPickupTime,
        @WebParam(name = "arvFltTime", targetNamespace = "http://tempuri.org/")
        String arvFltTime,
        @WebParam(name = "DepFltTime", targetNamespace = "http://tempuri.org/")
        String depFltTime,
        @WebParam(name = "ArvAirline", targetNamespace = "http://tempuri.org/")
        String arvAirline,
        @WebParam(name = "DepAirline", targetNamespace = "http://tempuri.org/")
        String depAirline,
        @WebParam(name = "FltType", targetNamespace = "http://tempuri.org/")
        String fltType,
        @WebParam(name = "origin", targetNamespace = "http://tempuri.org/")
        String origin,
        @WebParam(name = "FlyingTo", targetNamespace = "http://tempuri.org/")
        String flyingTo,
        @WebParam(name = "DepPassenger", targetNamespace = "http://tempuri.org/")
        String depPassenger,
        @WebParam(name = "DepDate", targetNamespace = "http://tempuri.org/")
        String depDate,
        @WebParam(name = "DepCity", targetNamespace = "http://tempuri.org/")
        String depCity,
        @WebParam(name = "DepFee", targetNamespace = "http://tempuri.org/")
        String depFee,
        @WebParam(name = "DepGratuity", targetNamespace = "http://tempuri.org/")
        String depGratuity,
        @WebParam(name = "Surcharge", targetNamespace = "http://tempuri.org/")
        String surcharge,
        @WebParam(name = "TravelerEmail", targetNamespace = "http://tempuri.org/")
        String travelerEmail,
        @WebParam(name = "specialinst", targetNamespace = "http://tempuri.org/")
        String specialinst,
        @WebParam(name = "Restype1", targetNamespace = "http://tempuri.org/")
        String restype1,
        @WebParam(name = "Restypedetail", targetNamespace = "http://tempuri.org/")
        String restypedetail,
        @WebParam(name = "BillTo", targetNamespace = "http://tempuri.org/")
        String billTo,
        @WebParam(name = "ReqArvTime", targetNamespace = "http://tempuri.org/")
        String reqArvTime,
        @WebParam(name = "IsSendEmail", targetNamespace = "http://tempuri.org/")
        boolean isSendEmail,
        @WebParam(name = "MailTo", targetNamespace = "http://tempuri.org/")
        String mailTo,
        @WebParam(name = "CharterDep", targetNamespace = "http://tempuri.org/")
        String charterDep,
        @WebParam(name = "CharterArv", targetNamespace = "http://tempuri.org/")
        String charterArv,
        @WebParam(name = "ClientId", targetNamespace = "http://tempuri.org/")
        String clientId,
        @WebParam(name = "SpecialServiceIDDep", targetNamespace = "http://tempuri.org/")
        String specialServiceIDDep,
        @WebParam(name = "DepServiceidNew", targetNamespace = "http://tempuri.org/")
        String depServiceidNew,
        @WebParam(name = "ArvServiceidNew", targetNamespace = "http://tempuri.org/")
        String arvServiceidNew,
        @WebParam(name = "ArvCancel", targetNamespace = "http://tempuri.org/")
        String arvCancel,
        @WebParam(name = "DepCancel", targetNamespace = "http://tempuri.org/")
        String depCancel,
        @WebParam(name = "CouponEmail", targetNamespace = "http://tempuri.org/")
        String couponEmail,
        @WebParam(name = "DiscCode", targetNamespace = "http://tempuri.org/")
        String discCode,
        @WebParam(name = "DiscAmt", targetNamespace = "http://tempuri.org/")
        String discAmt);

    /**
     * Allows us to get airport details based on specific input. Input is a string prefix of airport name.
     * 
     * @param preFix
     * @return
     *     returns com.scoa.roadrunner.connector.api.GetAirportResponse.GetAirportResult
     */
    @WebMethod(operationName = "GetAirport", action = "http://tempuri.org/GetAirport")
    @WebResult(name = "GetAirportResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAirport", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetAirport")
    @ResponseWrapper(localName = "GetAirportResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetAirportResponse")
    public com.scoa.roadrunner.connector.api.GetAirportResponse.GetAirportResult getAirport(
        @WebParam(name = "PreFix", targetNamespace = "http://tempuri.org/")
        String preFix);

    /**
     * This web method is for getting addresses for a customer. Inputs: customer Id and a prefix.
     * 
     * @param preFix
     * @param customerid
     * @return
     *     returns com.scoa.roadrunner.connector.api.GetAddressResponse.GetAddressResult
     */
    @WebMethod(operationName = "GetAddress", action = "http://tempuri.org/GetAddress")
    @WebResult(name = "GetAddressResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAddress", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetAddress")
    @ResponseWrapper(localName = "GetAddressResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetAddressResponse")
    public com.scoa.roadrunner.connector.api.GetAddressResponse.GetAddressResult getAddress(
        @WebParam(name = "Customerid", targetNamespace = "http://tempuri.org/")
        int customerid,
        @WebParam(name = "PreFix", targetNamespace = "http://tempuri.org/")
        String preFix);

    /**
     * This method is to get hotel details for specific city. Input: zip code, City name and hotel name string prefix.
     * 
     * @param preFix
     * @param zip
     * @param city
     * @return
     *     returns com.scoa.roadrunner.connector.api.GetHotelResponse.GetHotelResult
     */
    @WebMethod(operationName = "GetHotel", action = "http://tempuri.org/GetHotel")
    @WebResult(name = "GetHotelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetHotel", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetHotel")
    @ResponseWrapper(localName = "GetHotelResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetHotelResponse")
    public com.scoa.roadrunner.connector.api.GetHotelResponse.GetHotelResult getHotel(
        @WebParam(name = "Zip", targetNamespace = "http://tempuri.org/")
        String zip,
        @WebParam(name = "City", targetNamespace = "http://tempuri.org/")
        String city,
        @WebParam(name = "PreFix", targetNamespace = "http://tempuri.org/")
        String preFix);

    /**
     * This method is used to get airline details. Input is an airline prefix.
     * 
     * @param preFix
     * @return
     *     returns com.scoa.roadrunner.connector.api.GetAirLineResponse.GetAirLineResult
     */
    @WebMethod(operationName = "GetAirLine", action = "http://tempuri.org/GetAirLine")
    @WebResult(name = "GetAirLineResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAirLine", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetAirLine")
    @ResponseWrapper(localName = "GetAirLineResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetAirLineResponse")
    public com.scoa.roadrunner.connector.api.GetAirLineResponse.GetAirLineResult getAirLine(
        @WebParam(name = "PreFix", targetNamespace = "http://tempuri.org/")
        String preFix);

    /**
     * This method gets the Reservations for the CustomerID. Inputs:  CustomerID 
     * 
     * @param customerid
     * @return
     *     returns com.scoa.roadrunner.connector.api.GetMyReservationResponse.GetMyReservationResult
     */
    @WebMethod(operationName = "GetMyReservation", action = "http://tempuri.org/GetMyReservation")
    @WebResult(name = "GetMyReservationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMyReservation", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetMyReservation")
    @ResponseWrapper(localName = "GetMyReservationResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetMyReservationResponse")
    public com.scoa.roadrunner.connector.api.GetMyReservationResponse.GetMyReservationResult getMyReservation(
        @WebParam(name = "Customerid", targetNamespace = "http://tempuri.org/")
        int customerid);

    /**
     * This method allows new user registration. Input: EmailAddress, FName, LName, HomePhone, CellPhone, Number, Street, Unit, Complex, City, Zip, Password, Direction, Custid and CustType
     * 
     * @param zip
     * @param complex
     * @param direction
     * @param street
     * @param cellPhone
     * @param emailAddress
     * @param lName
     * @param number
     * @param homePhone
     * @param password
     * @param fName
     * @param city
     * @param unit
     * @param custid
     * @param custType
     * @return
     *     returns com.scoa.roadrunner.connector.api.NewUserRegistrationResponse.NewUserRegistrationResult
     */
    @WebMethod(operationName = "NewUserRegistration", action = "http://tempuri.org/NewUserRegistration")
    @WebResult(name = "NewUserRegistrationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NewUserRegistration", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.NewUserRegistration")
    @ResponseWrapper(localName = "NewUserRegistrationResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.NewUserRegistrationResponse")
    public com.scoa.roadrunner.connector.api.NewUserRegistrationResponse.NewUserRegistrationResult newUserRegistration(
        @WebParam(name = "EmailAddress", targetNamespace = "http://tempuri.org/")
        String emailAddress,
        @WebParam(name = "FName", targetNamespace = "http://tempuri.org/")
        String fName,
        @WebParam(name = "LName", targetNamespace = "http://tempuri.org/")
        String lName,
        @WebParam(name = "HomePhone", targetNamespace = "http://tempuri.org/")
        String homePhone,
        @WebParam(name = "CellPhone", targetNamespace = "http://tempuri.org/")
        String cellPhone,
        @WebParam(name = "Number", targetNamespace = "http://tempuri.org/")
        String number,
        @WebParam(name = "Street", targetNamespace = "http://tempuri.org/")
        String street,
        @WebParam(name = "Unit", targetNamespace = "http://tempuri.org/")
        String unit,
        @WebParam(name = "Complex", targetNamespace = "http://tempuri.org/")
        String complex,
        @WebParam(name = "City", targetNamespace = "http://tempuri.org/")
        String city,
        @WebParam(name = "Zip", targetNamespace = "http://tempuri.org/")
        String zip,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "Direction", targetNamespace = "http://tempuri.org/")
        String direction,
        @WebParam(name = "Custid", targetNamespace = "http://tempuri.org/")
        int custid,
        @WebParam(name = "CustType", targetNamespace = "http://tempuri.org/")
        int custType);

    /**
     * Allows to fetch the zip codes for specific city. Input: City name as a prefix.
     * 
     * @param preFix
     * @return
     *     returns com.scoa.roadrunner.connector.api.GetCityZipPairResponse.GetCityZipPairResult
     */
    @WebMethod(operationName = "GetCityZipPair", action = "http://tempuri.org/GetCityZipPair")
    @WebResult(name = "GetCityZipPairResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCityZipPair", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetCityZipPair")
    @ResponseWrapper(localName = "GetCityZipPairResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetCityZipPairResponse")
    public com.scoa.roadrunner.connector.api.GetCityZipPairResponse.GetCityZipPairResult getCityZipPair(
        @WebParam(name = "PreFix", targetNamespace = "http://tempuri.org/")
        String preFix);

    /**
     * The method to cancel reservations
     * 
     * @param updateMode
     * @param resId
     * @return
     *     returns com.scoa.roadrunner.connector.api.CancelReservationResponse.CancelReservationResult
     */
    @WebMethod(operationName = "CancelReservation", action = "http://tempuri.org/CancelReservation")
    @WebResult(name = "CancelReservationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelReservation", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.CancelReservation")
    @ResponseWrapper(localName = "CancelReservationResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.CancelReservationResponse")
    public com.scoa.roadrunner.connector.api.CancelReservationResponse.CancelReservationResult cancelReservation(
        @WebParam(name = "UpdateMode", targetNamespace = "http://tempuri.org/")
        int updateMode,
        @WebParam(name = "ResId", targetNamespace = "http://tempuri.org/")
        int resId);

    /**
     * This method allows a customer to get the estimiated pickup time for a reservation. Input: Phone no., reservation no. and customer last name.
     * 
     * @param res
     * @param lname
     * @param phone
     * @return
     *     returns com.scoa.roadrunner.connector.api.GetPickupETAForReservationResponse.GetPickupETAForReservationResult
     */
    @WebMethod(operationName = "GetPickupETAForReservation", action = "http://tempuri.org/GetPickupETAForReservation")
    @WebResult(name = "GetPickupETAForReservationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPickupETAForReservation", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetPickupETAForReservation")
    @ResponseWrapper(localName = "GetPickupETAForReservationResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.GetPickupETAForReservationResponse")
    public com.scoa.roadrunner.connector.api.GetPickupETAForReservationResponse.GetPickupETAForReservationResult getPickupETAForReservation(
        @WebParam(name = "phone", targetNamespace = "http://tempuri.org/")
        String phone,
        @WebParam(name = "res", targetNamespace = "http://tempuri.org/")
        int res,
        @WebParam(name = "lname", targetNamespace = "http://tempuri.org/")
        String lname);

    /**
     * This method gets the reservation details for Email.
     * 
     * @param reservationNo
     * @return
     *     returns com.scoa.roadrunner.connector.api.EmailResDetailsResponse.EmailResDetailsResult
     */
    @WebMethod(operationName = "EmailResDetails", action = "http://tempuri.org/EmailResDetails")
    @WebResult(name = "EmailResDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EmailResDetails", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.EmailResDetails")
    @ResponseWrapper(localName = "EmailResDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.EmailResDetailsResponse")
    public com.scoa.roadrunner.connector.api.EmailResDetailsResponse.EmailResDetailsResult emailResDetails(
        @WebParam(name = "ReservationNo", targetNamespace = "http://tempuri.org/")
        int reservationNo);

    /**
     * This method gets the payment details for Email.
     * 
     * @param reservationNo
     * @return
     *     returns com.scoa.roadrunner.connector.api.EmailPaymentDetailsResponse.EmailPaymentDetailsResult
     */
    @WebMethod(operationName = "EmailPaymentDetails", action = "http://tempuri.org/EmailPaymentDetails")
    @WebResult(name = "EmailPaymentDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EmailPaymentDetails", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.EmailPaymentDetails")
    @ResponseWrapper(localName = "EmailPaymentDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.EmailPaymentDetailsResponse")
    public com.scoa.roadrunner.connector.api.EmailPaymentDetailsResponse.EmailPaymentDetailsResult emailPaymentDetails(
        @WebParam(name = "ReservationNo", targetNamespace = "http://tempuri.org/")
        int reservationNo);

    /**
     * This method for Charge creditcards transactions.
     * 
     * @param custId
     * @param transId
     * @param qgUser
     * @param userName
     * @param vaultKey
     * @return
     *     returns com.scoa.roadrunner.connector.api.ChargeNowFromQGWithCustIDResponse.ChargeNowFromQGWithCustIDResult
     */
    @WebMethod(operationName = "ChargeNowFromQGWithCustID", action = "http://tempuri.org/ChargeNowFromQGWithCustID")
    @WebResult(name = "ChargeNowFromQGWithCustIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChargeNowFromQGWithCustID", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.ChargeNowFromQGWithCustID")
    @ResponseWrapper(localName = "ChargeNowFromQGWithCustIDResponse", targetNamespace = "http://tempuri.org/", className = "com.scoa.roadrunner.connector.api.ChargeNowFromQGWithCustIDResponse")
    public com.scoa.roadrunner.connector.api.ChargeNowFromQGWithCustIDResponse.ChargeNowFromQGWithCustIDResult chargeNowFromQGWithCustID(
        @WebParam(name = "TransId", targetNamespace = "http://tempuri.org/")
        int transId,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "QGUser", targetNamespace = "http://tempuri.org/")
        String qgUser,
        @WebParam(name = "VaultKey", targetNamespace = "http://tempuri.org/")
        String vaultKey,
        @WebParam(name = "CustId", targetNamespace = "http://tempuri.org/")
        int custId);

}
